---
include:
  # - board: nice_nano_v2
  - board: nice_nano
    shield: kebodo_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: nrfmicro_13
    shield: kebodo_right
  - board: nrfmicro_13
    shield: settings_reset
  # - board: nice_nano_v2
  - board: nice_nano
    shield: settings_reset

