---
include:
  - board: nice_nano
    shield: kebodo_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: nrfmicro/nrf52840
    shield: kebodo_right
  - board: nrfmicro/nrf52840
    shield: settings_reset
  - board: nice_nano
    shield: settings_reset
